Fix warning if no options have been created yet
isotope/core pull request #2203
Opened 2021-03-03 14:11 UTC by fritzmg

This PR fixes the following error:

```
ErrorException:
Warning: Invalid argument supplied for foreach()

  at vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Model\Attribute.php:270
  at Isotope\Model\Attribute->saveToDCA()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Model\Attribute\AbstractAttributeWithOptions.php:401)
  at Isotope\Model\Attribute\AbstractAttributeWithOptions->saveToDCA()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Model\Attribute\SelectMenu.php:47)
  at Isotope\Model\Attribute\SelectMenu->saveToDCA()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Backend\Product\DcaManager.php:118)
  at Isotope\Backend\Product\DcaManager->addAttributes()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Backend\Product\DcaManager.php:40)
  at Isotope\Backend\Product\DcaManager->initialize()
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaLoader.php:118)
  at Contao\DcaLoader->loadDcaFiles()
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaLoader.php:70)
  at Contao\DcaLoader->load()
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:1362)
  at Contao\Controller::loadDataContainer()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Backend\ProductType\Permission.php:44)
  at Isotope\Backend\ProductType\Permission::check()
     (vendor\contao\core-bundle\src\Resources\contao\drivers\DC_Table.php:202)
  at Contao\DC_Table->__construct()
     (vendor\contao\core-bundle\src\Resources\contao\classes\Backend.php:411)
  at Contao\Backend->getBackendModule()
     (vendor\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor\contao\core-bundle\src\Controller\BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor\symfony\http-kernel\HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor\symfony\http-kernel\HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web\index.php:31)
  at require('web\\index.php')
     (web\app.php:4)     
```

This happens if no options for a select/radio attribute have been created yet.

2021-03-31 08:33 UTC, aschempp commented
Unfortunately, Isotope 2.7 still supports PHP 5, therefore we can't use `??`. Can you update the PR to create a separate variable etc.?

2021-03-31 08:33 UTC, aschempp requested changes
Unfortunately, Isotope 2.7 still supports PHP 5, therefore we can't use ??. Can you update the PR to create a separate variable etc.?

2021-04-01 12:21 UTC, fritzmg commented
Meh, you guys should have dropped PHP 5 support for `2.7` 😁. Done.

2021-04-07 06:24 UTC, aschempp approved these changes

2021-04-07 07:20 UTC, operatorone commented
Just applied the fix and got the following output:

```
09:18:29 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod". Message: "Call to undefined method Isotope\Model\AttributeOption::getLanguageId()" ["exception" => Error { …},"command" => "cache:warmup --env=prod","message" => "Call to undefined method Isotope\Model\AttributeOption::getLanguageId()"]

In Attribute.php line 263:
                                                                               
Attempted to call an undefined method named "getLanguageId" of class "Isotope\Model\AttributeOption".
```

2021-04-07 07:45 UTC, fritzmg commented
@operatorone how did you apply this fix? It won't work if you only applied this fix manually. You would need to to install the `2.7` branch.

2021-04-07 08:44 UTC, operatorone commented
> @operatorone how did you apply this fix? It won't work if you only applied this fix manually. You would need to to install the PR's branch of my fork.

I updated to 2.7.1 before and replaced the file with the fixed code from github.

2021-04-07 08:50 UTC, fritzmg commented
@operatorone does your `system/modules/isotope/library/Isotope/Model/AttributeOption.php` file not contain this?

https://github.com/isotope/core/blob/f22f6e3a27db8d870e8daeb6923b8930a9acee03/system/modules/isotope/library/Isotope/Model/AttributeOption.php#L49-L60

In any case, your issue seems to be unrelated to this PR.

2021-04-07 09:20 UTC, operatorone commented
> @operatorone does your `system/modules/isotope/library/Isotope/Model/AttributeOption.php` file not contain this?
> 
> https://github.com/isotope/core/blob/f22f6e3a27db8d870e8daeb6923b8930a9acee03/system/modules/isotope/library/Isotope/Model/AttributeOption.php#L49-L60
> 
> In any case, your issue seems to be unrelated to this PR.

No, it didn't contain these lines and new errors occur on cache warmup.

`Argument 1 passed to Isotope\Model\AttributeOption::findByAttribute() must   
  implement interface Isotope\Interfaces\IsotopeAttributeWithOptions, instanc  
  e of Isotope\Model\Attribute\TextField given, called in /home/www/contao4_u  
  pd/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model  
  /Attribute.php on line 260`

I will do the update again, to see if it changes something.

2021-04-07 09:30 UTC, fritzmg commented
> No, it didn't contain these lines

Then something is wrong with your setup - because that should definitely be there in `2.7.1`.

2021-04-07 10:14 UTC, operatorone commented
Ok, I updated again to 2.7.1 to be sure everything is up to date. Then I took the file Attribute.php with the fix here from Github a cache clear and warmup. Still getting this error.

` Argument 1 passed to Isotope\Model\AttributeOption::findByAttribute() must implement interface Isotope\Interfaces\IsotopeAttributeWithOptions, instance of Isotope\Model\Attribute\TextField given, called in /home/www/contao4_u  
  pd/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Attribute.php on line 260`

Theses are the lines from my composer.json

```
"isotope/isotope-core": "2.7.*",
"isotope/isotope_documents": "^1.0",
```

I also checked AttributeOption.php. The mentioned lines are there.

2021-04-07 10:16 UTC, fritzmg commented
Please post that in a separate issue. As already said, this error is not related to this PR.

2021-04-07 10:35 UTC, operatorone commented
Ok, will do.

2021-05-25 13:28 UTC, merged