fix request cache and some warnings in the debug mode
isotope/core pull request #2285
Opened 2022-04-11 08:45 UTC by MDevster

2022-04-20 18:57 UTC, aschempp requested changes
Please always use `??` where possible and not `isset`.

Also, this is a bit confusing because it mixes a possible bugfix (Cache) with tons of CS fixes. Can you please split that into a separate PR?

2022-04-20 18:57 UTC, aschempp commented on system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php
> +                    if (isset($v['exclude']) && BackendUser::getInstance()->hasAccess($strTable . '::' . $k, 'alexf')) {
this would also be to `true` if `$v['exclude'] = false`

2022-04-20 18:57 UTC, aschempp commented on system/modules/isotope/library/Isotope/BackendModule/InitializeListener.php
> +                if (isset($arrConfig['tables']) && \is_array($arrConfig['tables'])) {
```suggestion
                if (\is_array($arrConfig['tables'] ?? null)) {
```

2022-04-20 18:57 UTC, aschempp commented on system/modules/isotope/library/Isotope/Model/Attribute.php
> +                    if (isset($option['group'])) {
```suggestion
                    if ($option['group'] ?? false) {
```

2022-04-20 18:57 UTC, aschempp commented on system/modules/isotope/library/Isotope/Module/ProductFilter.php
> +                [$sortingField, $sortingDirection] = explode(':', Input::post('sorting'));
`$sortingField` would no longer be set?

2022-04-20 18:57 UTC, aschempp commented on system/modules/isotope/library/Isotope/Model/RequestCache.php
> +        if ($this->store_id != 0) {
Can you please split this to a separate PR?

2022-04-26 15:05 UTC, aschempp commented
I have incorporated all of the php8 fixes into the 2.8 branch. If you'd allow me push access to your repo, I could update this PR for you so it only contains the request cache changes 😊

2022-04-26 17:15 UTC, MDevster commented
@aschempp The access is granted

2022-04-26 19:49 UTC, aschempp commented
PR updated. Can you please elaborate on the change request? A store ID of `0` is totally valid, so I don't see why this should be changed?

2022-05-23 08:51 UTC, aschempp commented
ping @MDevster

2022-06-09 06:58 UTC, MDevster commented
Unfortunately, I can no longer understand exactly because the changes arose from a support ticket and we just quickly helped the user that the store in Ethiopia is running again. His admin was probably not available. You can remove the change, he will contact us again after an update if necessary ;)

2022-06-16 07:37 UTC, closed without merging