Fix php8 array access errors
isotope/core pull request #2291
Opened 2022-05-01 11:05 UTC by fritzmg

This PR fixes some array access errors under PHP 8.

2022-05-02 07:36 UTC, Toflar approved these changes

2022-05-18 19:12 UTC, aschempp requested changes

2022-05-18 19:12 UTC, aschempp commented on system/modules/isotope/library/Isotope/Backend/Module/Callback.php
> +                || ($arrData['eval']['multiple'] ?? false && !$arrData['eval']['csv'] ?? false)
```suggestion
            if (($arrData['attributes']['dynamic'] ?? false)
                || (($arrData['eval']['multiple'] ?? false) && !($arrData['eval']['csv'] ?? false))
```

2022-05-18 19:12 UTC, aschempp commented on system/modules/isotope/library/Isotope/Backend/Module/Callback.php
> +            if ($arrData['attributes']['fe_search'] ?? false && !$arrData['attributes']['dynamic'] ?? false) {
```suggestion
            if (($arrData['attributes']['fe_search'] ?? false) && !($arrData['attributes']['dynamic'] ?? false)) {
```

2022-05-23 08:46 UTC, aschempp approved these changes

2022-05-23 08:46 UTC, merged

2022-05-23 10:43 UTC, aschempp commented
Thank you @fritzmg