Allow getGallery to use different Isotope Galleries
isotope/core pull request #2461
Opened 2023-06-09 15:53 UTC by bright-cloud-studio

We have a Product Reader page where we have multiple galleries being displayed. We wanted the ability to pick a different Isotope Gallery (Store configuration > Galleries) so I've added to getGallery a second parameter which is null by default but can be the ID of which gallery you want. Below that, if the ID is detected it replaces the current on inside $arrConfig.

I've tested this and it works perfectly. Feel free to change to any style you'd like, but for a three line change this adds very helpful functionality.

2023-06-16 07:53 UTC, aschempp requested changes
Please adjust the coding style. Also, will this work with the `$currentGallery` cache?

2023-06-16 07:53 UTC, aschempp commented on system/modules/isotope/library/Isotope/Model/Product/Standard.php
> +        $objTemplate->getGallery = function ($strAttribute, $isoGalleryId=null) use ($objProduct, $arrConfig, &$currentGallery) {
```suggestion
        $objTemplate->getGallery = function ($strAttribute, $galleryId=null) use ($objProduct, $arrConfig, &$currentGallery) {
```

2023-06-16 07:53 UTC, aschempp commented on system/modules/isotope/library/Isotope/Model/Product/Standard.php
> +                $arrConfig['gallery'] = $isoGalleryId;
```suggestion
            if(!is_null($isoGalleryId)) {
                $arrConfig['gallery'] = $galleryId;
            }
```

2023-06-16 14:51 UTC, bright-cloud-studio commented
I always tend to add iso to variable names when I am customizing something with Isotope but that doesn't make sense if I'm trying to add to the actual project. I've changed to the naming convention you suggested.

I can't say I am entirely sure what $currentGallery cache is, but we have been using this change on two different sites for a week or two now with no noticable issues.

2023-06-19 07:36 UTC, aschempp commented
> I can't say I am entirely sure what $currentGallery cache is, but we have been using this change on two different sites for a week or two now with no noticable issues.

I think this would only be a problem if you would try to use two different galleries on the same attribute in the same product (e.g. for the main image and for thumbnails). I'll look into this after merging the PR 😊

2023-08-08 14:28 UTC, bright-cloud-studio commented
So, another developer here was using my modification here and ran into the issue you predicted. This does not work when using the same image attribute for generateMainImage and generateGallery. Any suggestions on where to look next to adjust this? It looks like the getGallery function is called in ProductCollection.php in the addToTemplate function. Does that sound right?

2023-08-11 09:17 UTC, aschempp commented
I guess the easiest fix would be to remove the `$currentGallery` cache… or improve the cache to better handle configs.

2023-09-12 23:06 UTC, aschempp approved these changes

2023-09-12 23:15 UTC, merged

2023-09-13 12:21 UTC, bright-cloud-studio commented
I know in the grand scheme of things this is basically nothing, but I've never contributed to a piece of software I've used before. Pretty darn cool if you ask me.

2023-09-16 18:10 UTC, aschempp commented
Open Source FTW! ❤️