switch first report member guests to apexcharts lib
isotope/core pull request #2483
Opened 2023-08-07 21:08 UTC by error08

My suggestion to replace the outdated xchart library with the modern apexcharts library.

With this PR I only changed the report MemberGuests.

Next I would change the SalesTotal, then the D3 Lib and the xcharts can be removed.

If this fits, the next PR will follow soon.
In addition, I plan to include the conversation rate in sales.

2023-08-11 08:41 UTC, aschempp commented
Great enhancement, thanks a lot! Can we update the `initializeChart` method instead of transforming the data for apexcharts? And could you rebase the pull request on Isotope 2.9 (or I can do that)?

Also I would prefer to remove the unnecessary plugin files and fix some code style. Let me know if I should apply that or you will.

2023-08-11 10:16 UTC, error08 commented
Sure! I will refactor the initializeChart function and rebase the PR to 2.9. When I have trouble with the rebasing, I will contact you.

2023-08-14 18:47 UTC, error08 commented
I had no idea how to more simplify the initializeChart function. For grouping the data, the time range is relevant. Later for the chart generation it is no longer necessary.

2023-08-14 19:26 UTC, error08 commented
_"Also I would prefer to remove the unnecessary plugin files and fix some code style. Let me know if I should apply that or you will."_

Yes sure! But with my next PR regarding sales_total. At the moment sales_total still requires the old libraries.

2023-08-16 05:39 UTC, aschempp commented
Thanks a lot! I did mean to remove unnecessary files from the `apexcharts` folder, since we only seem to use one JS file (and probably some CSS), not all of the UMD stuff etc.

2023-08-22 21:44 UTC, error08 commented
I not sure if the lib works correct without the locale files. In my tests it seems it works.

2023-08-27 19:57 UTC, aschempp requested changes
Looks very good! Just some minor nitpicks then I think we can merge this 🎉

2023-08-27 19:57 UTC, aschempp commented on system/modules/isotope_reports/library/Isotope/Report/MembersGuests.php
> +
Please remove these empty line changes

2023-08-27 19:57 UTC, aschempp commented on system/modules/isotope_reports/templates/iso_report_members_guests.html5
> +  <script src="<?= \Haste\Util\Debug::uncompressedFile('system/modules/isotope_reports/assets/apexcharts/apexcharts.min.js') ?>"></script>
I think we can safely stop using `Debug::uncompressedFile` here, the feature is not included in Haste 5 anyway 😅

2023-08-27 19:57 UTC, aschempp commented on system/modules/isotope_reports/templates/iso_report_members_guests.html5
> +          text: <?= '"' . $GLOBALS['TL_LANG']['ISO_REPORT']['sales#'] . '"' ?>,
```suggestion
          text: "<?= $GLOBALS['TL_LANG']['ISO_REPORT']['sales#'] ?>",
```

2023-08-27 21:34 UTC, error08 commented
Please wait for merging the PR, I found an error in the weekly and daily view. Here is a difference between the chart and table. The bug seems to have existed for a long time.

2023-09-01 12:11 UTC, aschempp commented
> in the function `initializeChart` the chart and the table starts with different time range. (e.g. day or week) Is there a specific reason for?

I honestly have no idea, it has been at least 5 years since I touched that 😂 It's not about monday or sunday start of the week, right?

2023-09-01 17:08 UTC, error08 commented
I removed it. Now I think the PR is complete.

2023-09-08 15:21 UTC, aschempp approved these changes

2023-09-08 15:21 UTC, merged

2023-09-08 15:21 UTC, aschempp commented
Thank you @error08 !